name: OpenDataVis
title: OpenDataVis | A blog theme for Jekyll
description: An Open Source Code Repository for Data Visualisations
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: sskrupan@gmail.com
disqus_username: opendatavis
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml